# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InvestGame' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InvestGame
	pod 'Tibei'
  target 'InvestGameiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InvestGameiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InvestGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InvestGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


target 'mobileInvestGame' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobileInvestGame
	pod 'Tibei'
  target 'mobileInvestGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobileInvestGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
